//@ui5-bundle com/triscu/mop/Component-preload.js
sap.ui.require.preload({
	"com/triscu/mop/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(t,e,n){function s(t){return t&&t.__esModule&&typeof t.default!=="undefined"?t.default:t}const i=e["support"];const o=s(n);const c=t.extend("com.triscu.mop.Component",{metadata:{manifest:"json"},init:function e(){t.prototype.init.call(this);this.setModel(o.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function t(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!i.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}});return c});
},
	"com/triscu/mop/controller/App.controller.js":function(){sap.ui.define(["./BaseController"],function(e){function t(e){return e&&e.__esModule&&typeof e.default!=="undefined"?e.default:e}const n=t(e);const o=n.extend("com.triscu.mop.controller.App",{onInit:function e(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}});return o});
},
	"com/triscu/mop/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){const o=e.extend("com.triscu.mop.controller.BaseController",{getOwnerComponent:function t(){return e.prototype.getOwnerComponent.call(this)},getRouter:function e(){return t.getRouterFor(this)},getResourceBundle:function e(){const t=this.getOwnerComponent().getModel("i18n");return t.getResourceBundle()},getModel:function e(t){return this.getView().getModel(t)},setModel:function e(t,n){this.getView().setModel(t,n);return this},navTo:function e(t,n,o){this.getRouter().navTo(t,n,undefined,o)},onNavBack:function e(){const t=n.getInstance().getPreviousHash();if(t!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}});return o});
},
	"com/triscu/mop/controller/Main.controller.js":function(){sap.ui.define(["sap/m/MessageBox","./BaseController","../model/formatter"],function(o,t,e){function n(o){return o&&o.__esModule&&typeof o.default!=="undefined"?o.default:o}const r=n(t);const s=n(e);const c=r.extend("com.triscu.mop.controller.Main",{constructor:function o(){r.prototype.constructor.apply(this,arguments);this.formatter=s},sayHello:function t(){o.show("Hello World!")}});return c});
},
	"com/triscu/mop/i18n/i18n.properties":'appTitle=mop\nappDescription=UI5 Application mop\nbtnText=Say Hello',
	"com/triscu/mop/i18n/i18n_de.properties":'appTitle=mop\nappDescription=UI5 Application mop\nbtnText=Sag Hallo',
	"com/triscu/mop/i18n/i18n_en.properties":'appTitle=mop\nappDescription=UI5 Application mop\nbtnText=hai salut',
	"com/triscu/mop/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.triscu.mop","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.triscu.mop.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.96.16","libs":{"sap.ui.core":{},"sap.ui.layout":{},"sap.ui.unified":{},"sap.m":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.triscu.mop.i18n.i18n"}}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.triscu.mop.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"com/triscu/mop/model/formatter.js":function(){sap.ui.define([],function(){var r={formatValue:r=>{if(!r){return""}try{return parseFloat(r).toFixed(2)}catch(t){return r}}};return r});
},
	"com/triscu/mop/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,n,i){var d={createDeviceModel:()=>{const d=new e(i);d.setDefaultBindingMode(n.OneWay);return d}};return d});
},
	"com/triscu/mop/view/App.view.xml":'<mvc:View\n\tcontrollerName="com.triscu.mop.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" /></mvc:View>',
	"com/triscu/mop/view/Main.view.xml":'<mvc:View\n\tcontrollerName="com.triscu.mop.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><MessagePage\n\t\ttitle="{i18n>appTitle}"\n\t\ttext="{i18n>appTitle}"\n\t\ticon="sap-icon://accept"\n\t\tid="page"\n\t\tdescription="{i18n>appDescription}"><buttons><Button\n\t\t\t\ttext="{i18n>btnText}"\n\t\t\t\tpress="sayHello" /></buttons></MessagePage></mvc:View>'
});
